### ISSUE TITLE
你这项目太大了吧，我只想看微信上拉那个动画，还有你这项目 在android  2.3.3 打开不好用，全是错误，没有办法运行

### ISSUE THREAD

**Issue by JunnanLee** [renjianan/SimpleBrowser#6]
你这项目太大了吧，我只想看微信上拉那个动画，还有你这项目 在android  2.3.3 打开不好用，全是错误，没有办法运行

**Comment by renjianan** [comment]
微信上拉的在develop_recycler，另外我是在Android Studio3.0上开发的，你把gradle版本，依赖改一下就能在 2.3.3 上用了
